const shoes = [
  {
    id: 1,
    name: "KSL 01",
    price: "2000",
    rating: 4.5,
    image: "shoe.jpg",
    color: "black",
    size: "8",
    brand: "KSL",
    category: "shoes",
    type: "Loafers",
    designTemplate: "2",
  },
  {
    id: 2,
    name: "KSL 02",
    price: "2500",
    rating: 4.5,
    image: "shoe2.png",
    color: "antiquewhite",
    size: "2",
    brand: "KSL",
    category: "shoes",
    type: "Loafers",
    designTemplate: "2",
  },
  {
    id: 3,
    name: "KSL 03",
    price: "2000",
    rating: 4.5,
    image: "shoe2.png",
    color: "black",
    size: "8",
    brand: "KSL",
    category: "shoes",
    type: "Sneakers",
    designTemplate: "3",
  },
  {
    id: 4,
    name: "KSL 04",
    price: "3000",
    rating: 4.5,
    image: "shoe.jpg",
    color: "red",
    size: "8",
    brand: "KSL",
    category: "shoes",
    type: "Sneakers",
    designTemplate: "3+",
  },
  {
    id: 5,
    name: "NIKE",
    price: "5000",
    rating: 4.5,
    image: "shoe3.jpg",
    color: "red",
    size: "8",
    brand: "NIKE",
    category: "shoes",
    type: "Sneakers",
    designTemplate: "2",
  },
  {
    id: 6,
    name: "NIKE",
    price: "3000",
    rating: 4.5,
    image: "shoe4.jpg",
    color: "pink",
    size: "8",
    brand: "NIKE",
    category: "shoes",
    type: "loafers",
    designTemplate: "2",
  },
  {
    id: 7,
    name: "NIKE",
    price: "6000",
    rating: 4.5,
    image: "shoe5.jpg",
    color: "pink",
    size: "8",
    brand: "NIKE",
    category: "shoes",
    type: "Sneakers",
    designTemplate: "3",
  },
];

export default shoes;
